"""add_api_token

Revision ID: a0db672315b9
Revises: 09ed8879ee41
Create Date: 2026-07-07 11:49:34.835067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0db672315b9'
down_revision = '09ed8879ee41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_token'))
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
